---

- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    keyserver: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    mode: '644'
    update_cache: yes
    state: present

- name: Create systemd configuration directory for Docker service (systemd)
  file:
    dest: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  when: docker_opts != ""

- name: Set docker daemon options (systemd)
  copy:
    content: |
      [Service]
      Environment="DOCKER_OPTS={{ docker_opts.rstrip('\n') }}"
    dest: /etc/systemd/system/docker.service.d/env.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart docker
  when:
    - docker_opts != ""

- name: Ensure docker daemon options used (systemd)
  template:
    src: docker.conf
    dest: /etc/systemd/system/docker.service.d/docker.conf
  notify:
    - Restart docker
  when: docker_opts != ""

- lineinfile:
    dest: "{{ item }}"
    regexp: ^dockremap.*
    line: dockremap:165536:65536
  with_items:
    - /etc/subuid
    - /etc/subgid

- name: Install (or update) docker package
  apt:
    name: "{{ docker_pkg_name }}"
    state: present
    allow_unauthenticated: yes

- name: Install pip, python-dev package with apt
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-dev
    - python-pip

- name: Install docker-compose
  pip:
    name: docker-compose
    state: present

- name: Ensure setuptools, docker-py and docker-compose with pip
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose

- name: Reload systemd
  command: systemctl daemon-reload

- name: Ensure docker is running
  service:
    name: docker
    state: started

- name: Add users to the docker group
  user:
    name:   "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{docker_group_members}}"
  when: docker_group_members is defined

- name: Set Docker kernel options
  include_tasks: kernel_options.yml
