version: '2.1'

services:


  postgres-airflow:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: airflow
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-db-initialiser:
    image: airflow:latest
    environment:
      INITIALISE: "true"
    depends_on:
      postgres-airflow:
        condition: service_healthy

